package com.pbids.sanqin.model.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pbids.sanqin.model.entity.FriendGroupDb;
import com.pbids.sanqin.model.entity.FriendGroupMemberDb;
import com.pbids.sanqin.model.entity.NewsArticle;
import com.pbids.sanqin.model.entity.SystemMessage;
import com.pbids.sanqin.model.entity.UserInfo;

import com.pbids.sanqin.model.entity.FriendGroupDbDao;
import com.pbids.sanqin.model.entity.FriendGroupMemberDbDao;
import com.pbids.sanqin.model.entity.NewsArticleDao;
import com.pbids.sanqin.model.entity.SystemMessageDao;
import com.pbids.sanqin.model.entity.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendGroupDbDaoConfig;
    private final DaoConfig friendGroupMemberDbDaoConfig;
    private final DaoConfig newsArticleDaoConfig;
    private final DaoConfig systemMessageDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final FriendGroupDbDao friendGroupDbDao;
    private final FriendGroupMemberDbDao friendGroupMemberDbDao;
    private final NewsArticleDao newsArticleDao;
    private final SystemMessageDao systemMessageDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendGroupDbDaoConfig = daoConfigMap.get(FriendGroupDbDao.class).clone();
        friendGroupDbDaoConfig.initIdentityScope(type);

        friendGroupMemberDbDaoConfig = daoConfigMap.get(FriendGroupMemberDbDao.class).clone();
        friendGroupMemberDbDaoConfig.initIdentityScope(type);

        newsArticleDaoConfig = daoConfigMap.get(NewsArticleDao.class).clone();
        newsArticleDaoConfig.initIdentityScope(type);

        systemMessageDaoConfig = daoConfigMap.get(SystemMessageDao.class).clone();
        systemMessageDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        friendGroupDbDao = new FriendGroupDbDao(friendGroupDbDaoConfig, this);
        friendGroupMemberDbDao = new FriendGroupMemberDbDao(friendGroupMemberDbDaoConfig, this);
        newsArticleDao = new NewsArticleDao(newsArticleDaoConfig, this);
        systemMessageDao = new SystemMessageDao(systemMessageDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(FriendGroupDb.class, friendGroupDbDao);
        registerDao(FriendGroupMemberDb.class, friendGroupMemberDbDao);
        registerDao(NewsArticle.class, newsArticleDao);
        registerDao(SystemMessage.class, systemMessageDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        friendGroupDbDaoConfig.clearIdentityScope();
        friendGroupMemberDbDaoConfig.clearIdentityScope();
        newsArticleDaoConfig.clearIdentityScope();
        systemMessageDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public FriendGroupDbDao getFriendGroupDbDao() {
        return friendGroupDbDao;
    }

    public FriendGroupMemberDbDao getFriendGroupMemberDbDao() {
        return friendGroupMemberDbDao;
    }

    public NewsArticleDao getNewsArticleDao() {
        return newsArticleDao;
    }

    public SystemMessageDao getSystemMessageDao() {
        return systemMessageDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
